/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as VerifyPendingRouteImport } from './routes/verify-pending'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as TenantRouteImport } from './routes/_tenant'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as LandlordRouteImport } from './routes/_landlord'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsPayRouteImport } from './routes/payments/pay'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as PaymentsReceiptPaymentIdRouteImport } from './routes/payments/receipt.$paymentId'
import { Route as TenantTenantUploadRouteImport } from './routes/_tenant.tenant.upload'
import { Route as TenantTenantReceiptsRouteImport } from './routes/_tenant.tenant.receipts'
import { Route as TenantTenantPaymentsRouteImport } from './routes/_tenant.tenant.payments'
import { Route as TenantTenantNotificationsRouteImport } from './routes/_tenant.tenant.notifications'
import { Route as TenantTenantDashboardRouteImport } from './routes/_tenant.tenant.dashboard'
import { Route as StudentStudentPaymentsRouteImport } from './routes/_student.student.payments'
import { Route as StudentStudentInboxRouteImport } from './routes/_student.student.inbox'
import { Route as StudentStudentDashboardRouteImport } from './routes/_student.student.dashboard'
import { Route as StudentStudentAppointmentsRouteImport } from './routes/_student.student.appointments'
import { Route as LandlordLandlordTenantsRouteImport } from './routes/_landlord.landlord.tenants'
import { Route as LandlordLandlordReceiptsRouteImport } from './routes/_landlord.landlord.receipts'
import { Route as LandlordLandlordPropertiesRouteImport } from './routes/_landlord.landlord.properties'
import { Route as LandlordLandlordNotificationsRouteImport } from './routes/_landlord.landlord.notifications'
import { Route as LandlordLandlordListingsRouteImport } from './routes/_landlord.landlord.listings'
import { Route as LandlordLandlordInboxRouteImport } from './routes/_landlord.landlord.inbox'
import { Route as LandlordLandlordDashboardRouteImport } from './routes/_landlord.landlord.dashboard'
import { Route as LandlordLandlordAppointmentsRouteImport } from './routes/_landlord.landlord.appointments'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminPaymentsRouteImport } from './routes/_admin.admin.payments'
import { Route as AdminAdminMessagesRouteImport } from './routes/_admin.admin.messages'
import { Route as AdminAdminListingsRouteImport } from './routes/_admin.admin.listings'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as StudentStudentListingsSavedRouteImport } from './routes/_student.student.listings.saved'
import { Route as LandlordLandlordPaymentsReviewRouteImport } from './routes/_landlord.landlord.payments.review'
import { Route as LandlordLandlordListingsCreateRouteImport } from './routes/_landlord.landlord.listings_.create'
import { Route as AdminAdminVerificationsStudentsRouteImport } from './routes/_admin.admin.verifications.students'
import { Route as AdminAdminVerificationsLandlordsRouteImport } from './routes/_admin.admin.verifications.landlords'
import { Route as LandlordLandlordListingsIdEditRouteImport } from './routes/_landlord.landlord.listings_.$id.edit'

const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPendingRoute = VerifyPendingRouteImport.update({
  id: '/verify-pending',
  path: '/verify-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/_tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/_landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsPayRoute = PaymentsPayRouteImport.update({
  id: '/payments/pay',
  path: '/payments/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MessagesRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsReceiptPaymentIdRoute =
  PaymentsReceiptPaymentIdRouteImport.update({
    id: '/payments/receipt/$paymentId',
    path: '/payments/receipt/$paymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TenantTenantUploadRoute = TenantTenantUploadRouteImport.update({
  id: '/tenant/upload',
  path: '/tenant/upload',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTenantReceiptsRoute = TenantTenantReceiptsRouteImport.update({
  id: '/tenant/receipts',
  path: '/tenant/receipts',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTenantPaymentsRoute = TenantTenantPaymentsRouteImport.update({
  id: '/tenant/payments',
  path: '/tenant/payments',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTenantNotificationsRoute =
  TenantTenantNotificationsRouteImport.update({
    id: '/tenant/notifications',
    path: '/tenant/notifications',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantTenantDashboardRoute = TenantTenantDashboardRouteImport.update({
  id: '/tenant/dashboard',
  path: '/tenant/dashboard',
  getParentRoute: () => TenantRoute,
} as any)
const StudentStudentPaymentsRoute = StudentStudentPaymentsRouteImport.update({
  id: '/student/payments',
  path: '/student/payments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentInboxRoute = StudentStudentInboxRouteImport.update({
  id: '/student/inbox',
  path: '/student/inbox',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentDashboardRoute = StudentStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentAppointmentsRoute =
  StudentStudentAppointmentsRouteImport.update({
    id: '/student/appointments',
    path: '/student/appointments',
    getParentRoute: () => StudentRoute,
  } as any)
const LandlordLandlordTenantsRoute = LandlordLandlordTenantsRouteImport.update({
  id: '/landlord/tenants',
  path: '/landlord/tenants',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordLandlordReceiptsRoute =
  LandlordLandlordReceiptsRouteImport.update({
    id: '/landlord/receipts',
    path: '/landlord/receipts',
    getParentRoute: () => LandlordRoute,
  } as any)
const LandlordLandlordPropertiesRoute =
  LandlordLandlordPropertiesRouteImport.update({
    id: '/landlord/properties',
    path: '/landlord/properties',
    getParentRoute: () => LandlordRoute,
  } as any)
const LandlordLandlordNotificationsRoute =
  LandlordLandlordNotificationsRouteImport.update({
    id: '/landlord/notifications',
    path: '/landlord/notifications',
    getParentRoute: () => LandlordRoute,
  } as any)
const LandlordLandlordListingsRoute =
  LandlordLandlordListingsRouteImport.update({
    id: '/landlord/listings',
    path: '/landlord/listings',
    getParentRoute: () => LandlordRoute,
  } as any)
const LandlordLandlordInboxRoute = LandlordLandlordInboxRouteImport.update({
  id: '/landlord/inbox',
  path: '/landlord/inbox',
  getParentRoute: () => LandlordRoute,
} as any)
const LandlordLandlordDashboardRoute =
  LandlordLandlordDashboardRouteImport.update({
    id: '/landlord/dashboard',
    path: '/landlord/dashboard',
    getParentRoute: () => LandlordRoute,
  } as any)
const LandlordLandlordAppointmentsRoute =
  LandlordLandlordAppointmentsRouteImport.update({
    id: '/landlord/appointments',
    path: '/landlord/appointments',
    getParentRoute: () => LandlordRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMessagesRoute = AdminAdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminListingsRoute = AdminAdminListingsRouteImport.update({
  id: '/admin/listings',
  path: '/admin/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const StudentStudentListingsSavedRoute =
  StudentStudentListingsSavedRouteImport.update({
    id: '/student/listings/saved',
    path: '/student/listings/saved',
    getParentRoute: () => StudentRoute,
  } as any)
const LandlordLandlordPaymentsReviewRoute =
  LandlordLandlordPaymentsReviewRouteImport.update({
    id: '/landlord/payments/review',
    path: '/landlord/payments/review',
    getParentRoute: () => LandlordRoute,
  } as any)
const LandlordLandlordListingsCreateRoute =
  LandlordLandlordListingsCreateRouteImport.update({
    id: '/landlord/listings_/create',
    path: '/landlord/listings/create',
    getParentRoute: () => LandlordRoute,
  } as any)
const AdminAdminVerificationsStudentsRoute =
  AdminAdminVerificationsStudentsRouteImport.update({
    id: '/admin/verifications/students',
    path: '/admin/verifications/students',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminVerificationsLandlordsRoute =
  AdminAdminVerificationsLandlordsRouteImport.update({
    id: '/admin/verifications/landlords',
    path: '/admin/verifications/landlords',
    getParentRoute: () => AdminRoute,
  } as any)
const LandlordLandlordListingsIdEditRoute =
  LandlordLandlordListingsIdEditRouteImport.update({
    id: '/landlord/listings_/$id/edit',
    path: '/landlord/listings/$id/edit',
    getParentRoute: () => LandlordRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/visits': typeof VisitsRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/payments/pay': typeof PaymentsPayRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/listings': typeof AdminAdminListingsRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/landlord/appointments': typeof LandlordLandlordAppointmentsRoute
  '/landlord/dashboard': typeof LandlordLandlordDashboardRoute
  '/landlord/inbox': typeof LandlordLandlordInboxRoute
  '/landlord/listings': typeof LandlordLandlordListingsRoute
  '/landlord/notifications': typeof LandlordLandlordNotificationsRoute
  '/landlord/properties': typeof LandlordLandlordPropertiesRoute
  '/landlord/receipts': typeof LandlordLandlordReceiptsRoute
  '/landlord/tenants': typeof LandlordLandlordTenantsRoute
  '/student/appointments': typeof StudentStudentAppointmentsRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/inbox': typeof StudentStudentInboxRoute
  '/student/payments': typeof StudentStudentPaymentsRoute
  '/tenant/dashboard': typeof TenantTenantDashboardRoute
  '/tenant/notifications': typeof TenantTenantNotificationsRoute
  '/tenant/payments': typeof TenantTenantPaymentsRoute
  '/tenant/receipts': typeof TenantTenantReceiptsRoute
  '/tenant/upload': typeof TenantTenantUploadRoute
  '/payments/receipt/$paymentId': typeof PaymentsReceiptPaymentIdRoute
  '/admin/verifications/landlords': typeof AdminAdminVerificationsLandlordsRoute
  '/admin/verifications/students': typeof AdminAdminVerificationsStudentsRoute
  '/landlord/listings/create': typeof LandlordLandlordListingsCreateRoute
  '/landlord/payments/review': typeof LandlordLandlordPaymentsReviewRoute
  '/student/listings/saved': typeof StudentStudentListingsSavedRoute
  '/landlord/listings/$id/edit': typeof LandlordLandlordListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/visits': typeof VisitsRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/payments/pay': typeof PaymentsPayRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/listings': typeof AdminAdminListingsRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/landlord/appointments': typeof LandlordLandlordAppointmentsRoute
  '/landlord/dashboard': typeof LandlordLandlordDashboardRoute
  '/landlord/inbox': typeof LandlordLandlordInboxRoute
  '/landlord/listings': typeof LandlordLandlordListingsRoute
  '/landlord/notifications': typeof LandlordLandlordNotificationsRoute
  '/landlord/properties': typeof LandlordLandlordPropertiesRoute
  '/landlord/receipts': typeof LandlordLandlordReceiptsRoute
  '/landlord/tenants': typeof LandlordLandlordTenantsRoute
  '/student/appointments': typeof StudentStudentAppointmentsRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/inbox': typeof StudentStudentInboxRoute
  '/student/payments': typeof StudentStudentPaymentsRoute
  '/tenant/dashboard': typeof TenantTenantDashboardRoute
  '/tenant/notifications': typeof TenantTenantNotificationsRoute
  '/tenant/payments': typeof TenantTenantPaymentsRoute
  '/tenant/receipts': typeof TenantTenantReceiptsRoute
  '/tenant/upload': typeof TenantTenantUploadRoute
  '/payments/receipt/$paymentId': typeof PaymentsReceiptPaymentIdRoute
  '/admin/verifications/landlords': typeof AdminAdminVerificationsLandlordsRoute
  '/admin/verifications/students': typeof AdminAdminVerificationsStudentsRoute
  '/landlord/listings/create': typeof LandlordLandlordListingsCreateRoute
  '/landlord/payments/review': typeof LandlordLandlordPaymentsReviewRoute
  '/student/listings/saved': typeof StudentStudentListingsSavedRoute
  '/landlord/listings/$id/edit': typeof LandlordLandlordListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_landlord': typeof LandlordRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/_tenant': typeof TenantRouteWithChildren
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/visits': typeof VisitsRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/payments/pay': typeof PaymentsPayRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/listings': typeof AdminAdminListingsRoute
  '/_admin/admin/messages': typeof AdminAdminMessagesRoute
  '/_admin/admin/payments': typeof AdminAdminPaymentsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_landlord/landlord/appointments': typeof LandlordLandlordAppointmentsRoute
  '/_landlord/landlord/dashboard': typeof LandlordLandlordDashboardRoute
  '/_landlord/landlord/inbox': typeof LandlordLandlordInboxRoute
  '/_landlord/landlord/listings': typeof LandlordLandlordListingsRoute
  '/_landlord/landlord/notifications': typeof LandlordLandlordNotificationsRoute
  '/_landlord/landlord/properties': typeof LandlordLandlordPropertiesRoute
  '/_landlord/landlord/receipts': typeof LandlordLandlordReceiptsRoute
  '/_landlord/landlord/tenants': typeof LandlordLandlordTenantsRoute
  '/_student/student/appointments': typeof StudentStudentAppointmentsRoute
  '/_student/student/dashboard': typeof StudentStudentDashboardRoute
  '/_student/student/inbox': typeof StudentStudentInboxRoute
  '/_student/student/payments': typeof StudentStudentPaymentsRoute
  '/_tenant/tenant/dashboard': typeof TenantTenantDashboardRoute
  '/_tenant/tenant/notifications': typeof TenantTenantNotificationsRoute
  '/_tenant/tenant/payments': typeof TenantTenantPaymentsRoute
  '/_tenant/tenant/receipts': typeof TenantTenantReceiptsRoute
  '/_tenant/tenant/upload': typeof TenantTenantUploadRoute
  '/payments/receipt/$paymentId': typeof PaymentsReceiptPaymentIdRoute
  '/_admin/admin/verifications/landlords': typeof AdminAdminVerificationsLandlordsRoute
  '/_admin/admin/verifications/students': typeof AdminAdminVerificationsStudentsRoute
  '/_landlord/landlord/listings_/create': typeof LandlordLandlordListingsCreateRoute
  '/_landlord/landlord/payments/review': typeof LandlordLandlordPaymentsReviewRoute
  '/_student/student/listings/saved': typeof StudentStudentListingsSavedRoute
  '/_landlord/landlord/listings_/$id/edit': typeof LandlordLandlordListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/forgot-password'
    | '/invite'
    | '/listings'
    | '/login'
    | '/messages'
    | '/profile'
    | '/search'
    | '/signup'
    | '/sso-callback'
    | '/verify-pending'
    | '/visits'
    | '/listing/$id'
    | '/messages/$threadId'
    | '/payments/pay'
    | '/admin/dashboard'
    | '/admin/listings'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/landlord/appointments'
    | '/landlord/dashboard'
    | '/landlord/inbox'
    | '/landlord/listings'
    | '/landlord/notifications'
    | '/landlord/properties'
    | '/landlord/receipts'
    | '/landlord/tenants'
    | '/student/appointments'
    | '/student/dashboard'
    | '/student/inbox'
    | '/student/payments'
    | '/tenant/dashboard'
    | '/tenant/notifications'
    | '/tenant/payments'
    | '/tenant/receipts'
    | '/tenant/upload'
    | '/payments/receipt/$paymentId'
    | '/admin/verifications/landlords'
    | '/admin/verifications/students'
    | '/landlord/listings/create'
    | '/landlord/payments/review'
    | '/student/listings/saved'
    | '/landlord/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/forgot-password'
    | '/invite'
    | '/listings'
    | '/login'
    | '/messages'
    | '/profile'
    | '/search'
    | '/signup'
    | '/sso-callback'
    | '/verify-pending'
    | '/visits'
    | '/listing/$id'
    | '/messages/$threadId'
    | '/payments/pay'
    | '/admin/dashboard'
    | '/admin/listings'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/landlord/appointments'
    | '/landlord/dashboard'
    | '/landlord/inbox'
    | '/landlord/listings'
    | '/landlord/notifications'
    | '/landlord/properties'
    | '/landlord/receipts'
    | '/landlord/tenants'
    | '/student/appointments'
    | '/student/dashboard'
    | '/student/inbox'
    | '/student/payments'
    | '/tenant/dashboard'
    | '/tenant/notifications'
    | '/tenant/payments'
    | '/tenant/receipts'
    | '/tenant/upload'
    | '/payments/receipt/$paymentId'
    | '/admin/verifications/landlords'
    | '/admin/verifications/students'
    | '/landlord/listings/create'
    | '/landlord/payments/review'
    | '/student/listings/saved'
    | '/landlord/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_landlord'
    | '/_student'
    | '/_tenant'
    | '/explore'
    | '/forgot-password'
    | '/invite'
    | '/listings'
    | '/login'
    | '/messages'
    | '/profile'
    | '/search'
    | '/signup'
    | '/sso-callback'
    | '/verify-pending'
    | '/visits'
    | '/listing/$id'
    | '/messages/$threadId'
    | '/payments/pay'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/listings'
    | '/_admin/admin/messages'
    | '/_admin/admin/payments'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/_landlord/landlord/appointments'
    | '/_landlord/landlord/dashboard'
    | '/_landlord/landlord/inbox'
    | '/_landlord/landlord/listings'
    | '/_landlord/landlord/notifications'
    | '/_landlord/landlord/properties'
    | '/_landlord/landlord/receipts'
    | '/_landlord/landlord/tenants'
    | '/_student/student/appointments'
    | '/_student/student/dashboard'
    | '/_student/student/inbox'
    | '/_student/student/payments'
    | '/_tenant/tenant/dashboard'
    | '/_tenant/tenant/notifications'
    | '/_tenant/tenant/payments'
    | '/_tenant/tenant/receipts'
    | '/_tenant/tenant/upload'
    | '/payments/receipt/$paymentId'
    | '/_admin/admin/verifications/landlords'
    | '/_admin/admin/verifications/students'
    | '/_landlord/landlord/listings_/create'
    | '/_landlord/landlord/payments/review'
    | '/_student/student/listings/saved'
    | '/_landlord/landlord/listings_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LandlordRoute: typeof LandlordRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TenantRoute: typeof TenantRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  VerifyPendingRoute: typeof VerifyPendingRoute
  VisitsRoute: typeof VisitsRoute
  ListingIdRoute: typeof ListingIdRoute
  PaymentsPayRoute: typeof PaymentsPayRoute
  PaymentsReceiptPaymentIdRoute: typeof PaymentsReceiptPaymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-pending': {
      id: '/verify-pending'
      path: '/verify-pending'
      fullPath: '/verify-pending'
      preLoaderRoute: typeof VerifyPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tenant': {
      id: '/_tenant'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landlord': {
      id: '/_landlord'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/pay': {
      id: '/payments/pay'
      path: '/payments/pay'
      fullPath: '/payments/pay'
      preLoaderRoute: typeof PaymentsPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/receipt/$paymentId': {
      id: '/payments/receipt/$paymentId'
      path: '/payments/receipt/$paymentId'
      fullPath: '/payments/receipt/$paymentId'
      preLoaderRoute: typeof PaymentsReceiptPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tenant/tenant/upload': {
      id: '/_tenant/tenant/upload'
      path: '/tenant/upload'
      fullPath: '/tenant/upload'
      preLoaderRoute: typeof TenantTenantUploadRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/tenant/receipts': {
      id: '/_tenant/tenant/receipts'
      path: '/tenant/receipts'
      fullPath: '/tenant/receipts'
      preLoaderRoute: typeof TenantTenantReceiptsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/tenant/payments': {
      id: '/_tenant/tenant/payments'
      path: '/tenant/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantTenantPaymentsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/tenant/notifications': {
      id: '/_tenant/tenant/notifications'
      path: '/tenant/notifications'
      fullPath: '/tenant/notifications'
      preLoaderRoute: typeof TenantTenantNotificationsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_tenant/tenant/dashboard': {
      id: '/_tenant/tenant/dashboard'
      path: '/tenant/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof TenantTenantDashboardRouteImport
      parentRoute: typeof TenantRoute
    }
    '/_student/student/payments': {
      id: '/_student/student/payments'
      path: '/student/payments'
      fullPath: '/student/payments'
      preLoaderRoute: typeof StudentStudentPaymentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/inbox': {
      id: '/_student/student/inbox'
      path: '/student/inbox'
      fullPath: '/student/inbox'
      preLoaderRoute: typeof StudentStudentInboxRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/dashboard': {
      id: '/_student/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentStudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/appointments': {
      id: '/_student/student/appointments'
      path: '/student/appointments'
      fullPath: '/student/appointments'
      preLoaderRoute: typeof StudentStudentAppointmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_landlord/landlord/tenants': {
      id: '/_landlord/landlord/tenants'
      path: '/landlord/tenants'
      fullPath: '/landlord/tenants'
      preLoaderRoute: typeof LandlordLandlordTenantsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/receipts': {
      id: '/_landlord/landlord/receipts'
      path: '/landlord/receipts'
      fullPath: '/landlord/receipts'
      preLoaderRoute: typeof LandlordLandlordReceiptsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/properties': {
      id: '/_landlord/landlord/properties'
      path: '/landlord/properties'
      fullPath: '/landlord/properties'
      preLoaderRoute: typeof LandlordLandlordPropertiesRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/notifications': {
      id: '/_landlord/landlord/notifications'
      path: '/landlord/notifications'
      fullPath: '/landlord/notifications'
      preLoaderRoute: typeof LandlordLandlordNotificationsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/listings': {
      id: '/_landlord/landlord/listings'
      path: '/landlord/listings'
      fullPath: '/landlord/listings'
      preLoaderRoute: typeof LandlordLandlordListingsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/inbox': {
      id: '/_landlord/landlord/inbox'
      path: '/landlord/inbox'
      fullPath: '/landlord/inbox'
      preLoaderRoute: typeof LandlordLandlordInboxRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/dashboard': {
      id: '/_landlord/landlord/dashboard'
      path: '/landlord/dashboard'
      fullPath: '/landlord/dashboard'
      preLoaderRoute: typeof LandlordLandlordDashboardRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/appointments': {
      id: '/_landlord/landlord/appointments'
      path: '/landlord/appointments'
      fullPath: '/landlord/appointments'
      preLoaderRoute: typeof LandlordLandlordAppointmentsRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/payments': {
      id: '/_admin/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/messages': {
      id: '/_admin/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/listings': {
      id: '/_admin/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminAdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/student/listings/saved': {
      id: '/_student/student/listings/saved'
      path: '/student/listings/saved'
      fullPath: '/student/listings/saved'
      preLoaderRoute: typeof StudentStudentListingsSavedRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_landlord/landlord/payments/review': {
      id: '/_landlord/landlord/payments/review'
      path: '/landlord/payments/review'
      fullPath: '/landlord/payments/review'
      preLoaderRoute: typeof LandlordLandlordPaymentsReviewRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_landlord/landlord/listings_/create': {
      id: '/_landlord/landlord/listings_/create'
      path: '/landlord/listings/create'
      fullPath: '/landlord/listings/create'
      preLoaderRoute: typeof LandlordLandlordListingsCreateRouteImport
      parentRoute: typeof LandlordRoute
    }
    '/_admin/admin/verifications/students': {
      id: '/_admin/admin/verifications/students'
      path: '/admin/verifications/students'
      fullPath: '/admin/verifications/students'
      preLoaderRoute: typeof AdminAdminVerificationsStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/verifications/landlords': {
      id: '/_admin/admin/verifications/landlords'
      path: '/admin/verifications/landlords'
      fullPath: '/admin/verifications/landlords'
      preLoaderRoute: typeof AdminAdminVerificationsLandlordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_landlord/landlord/listings_/$id/edit': {
      id: '/_landlord/landlord/listings_/$id/edit'
      path: '/landlord/listings/$id/edit'
      fullPath: '/landlord/listings/$id/edit'
      preLoaderRoute: typeof LandlordLandlordListingsIdEditRouteImport
      parentRoute: typeof LandlordRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminListingsRoute: typeof AdminAdminListingsRoute
  AdminAdminMessagesRoute: typeof AdminAdminMessagesRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminVerificationsLandlordsRoute: typeof AdminAdminVerificationsLandlordsRoute
  AdminAdminVerificationsStudentsRoute: typeof AdminAdminVerificationsStudentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminListingsRoute: AdminAdminListingsRoute,
  AdminAdminMessagesRoute: AdminAdminMessagesRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminVerificationsLandlordsRoute: AdminAdminVerificationsLandlordsRoute,
  AdminAdminVerificationsStudentsRoute: AdminAdminVerificationsStudentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LandlordRouteChildren {
  LandlordLandlordAppointmentsRoute: typeof LandlordLandlordAppointmentsRoute
  LandlordLandlordDashboardRoute: typeof LandlordLandlordDashboardRoute
  LandlordLandlordInboxRoute: typeof LandlordLandlordInboxRoute
  LandlordLandlordListingsRoute: typeof LandlordLandlordListingsRoute
  LandlordLandlordNotificationsRoute: typeof LandlordLandlordNotificationsRoute
  LandlordLandlordPropertiesRoute: typeof LandlordLandlordPropertiesRoute
  LandlordLandlordReceiptsRoute: typeof LandlordLandlordReceiptsRoute
  LandlordLandlordTenantsRoute: typeof LandlordLandlordTenantsRoute
  LandlordLandlordListingsCreateRoute: typeof LandlordLandlordListingsCreateRoute
  LandlordLandlordPaymentsReviewRoute: typeof LandlordLandlordPaymentsReviewRoute
  LandlordLandlordListingsIdEditRoute: typeof LandlordLandlordListingsIdEditRoute
}

const LandlordRouteChildren: LandlordRouteChildren = {
  LandlordLandlordAppointmentsRoute: LandlordLandlordAppointmentsRoute,
  LandlordLandlordDashboardRoute: LandlordLandlordDashboardRoute,
  LandlordLandlordInboxRoute: LandlordLandlordInboxRoute,
  LandlordLandlordListingsRoute: LandlordLandlordListingsRoute,
  LandlordLandlordNotificationsRoute: LandlordLandlordNotificationsRoute,
  LandlordLandlordPropertiesRoute: LandlordLandlordPropertiesRoute,
  LandlordLandlordReceiptsRoute: LandlordLandlordReceiptsRoute,
  LandlordLandlordTenantsRoute: LandlordLandlordTenantsRoute,
  LandlordLandlordListingsCreateRoute: LandlordLandlordListingsCreateRoute,
  LandlordLandlordPaymentsReviewRoute: LandlordLandlordPaymentsReviewRoute,
  LandlordLandlordListingsIdEditRoute: LandlordLandlordListingsIdEditRoute,
}

const LandlordRouteWithChildren = LandlordRoute._addFileChildren(
  LandlordRouteChildren,
)

interface StudentRouteChildren {
  StudentStudentAppointmentsRoute: typeof StudentStudentAppointmentsRoute
  StudentStudentDashboardRoute: typeof StudentStudentDashboardRoute
  StudentStudentInboxRoute: typeof StudentStudentInboxRoute
  StudentStudentPaymentsRoute: typeof StudentStudentPaymentsRoute
  StudentStudentListingsSavedRoute: typeof StudentStudentListingsSavedRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentAppointmentsRoute: StudentStudentAppointmentsRoute,
  StudentStudentDashboardRoute: StudentStudentDashboardRoute,
  StudentStudentInboxRoute: StudentStudentInboxRoute,
  StudentStudentPaymentsRoute: StudentStudentPaymentsRoute,
  StudentStudentListingsSavedRoute: StudentStudentListingsSavedRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TenantRouteChildren {
  TenantTenantDashboardRoute: typeof TenantTenantDashboardRoute
  TenantTenantNotificationsRoute: typeof TenantTenantNotificationsRoute
  TenantTenantPaymentsRoute: typeof TenantTenantPaymentsRoute
  TenantTenantReceiptsRoute: typeof TenantTenantReceiptsRoute
  TenantTenantUploadRoute: typeof TenantTenantUploadRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantTenantDashboardRoute: TenantTenantDashboardRoute,
  TenantTenantNotificationsRoute: TenantTenantNotificationsRoute,
  TenantTenantPaymentsRoute: TenantTenantPaymentsRoute,
  TenantTenantReceiptsRoute: TenantTenantReceiptsRoute,
  TenantTenantUploadRoute: TenantTenantUploadRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

interface MessagesRouteChildren {
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesThreadIdRoute: MessagesThreadIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LandlordRoute: LandlordRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TenantRoute: TenantRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  VerifyPendingRoute: VerifyPendingRoute,
  VisitsRoute: VisitsRoute,
  ListingIdRoute: ListingIdRoute,
  PaymentsPayRoute: PaymentsPayRoute,
  PaymentsReceiptPaymentIdRoute: PaymentsReceiptPaymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
